app.py

added MSP Displayport and fixed MSP dependencies

Added MSP DisplayPort feature

---

app.py

when ArduPilot #16441 gets merged

Add OSD sidebars option

---

app.py

Add options for VTOL frame types

---

app.py

Companion PR to  https://github.com/ArduPilot/ardupilot/pull/18838 for when that gets merged. Defines out AP_AIRSPEED at the vehicle level.

APP: build options add AP_AIRSPEED_ENABLED

---

app.py
templates/generate.html
templates/index.html
templates/index2.html

Adds an extra dropdown to select which branch is built. Also adds a second page for selecting the reset of the build options because they need to be updated based on the branch that is selected.
Currently only has branches from upstream - master and the plane, copter & rover stable branches, but this should work for any remote that has been added to the repo on the server (I tested by adding my own repo to my local one).
Also added Blimp vehicle option as a "driveby".

Add option to select branches

---

app.py

This adds Blimp and Heli as vehicle options.

Add Blimp and Heli as vehicle options

---

app.py
templates/index2.html

Fix the branch selection issues.

Fix branch selection, change Tracker to AntennaTracker

---

templates/index.html

This would let users know about the beta server running the new features and give feedback on the same,

Add beta server link to ask users to try out the beta features

---

static/js/add_build.js
templates/add_build.html

This pull request adds a new "Check/Uncheck All" feature to the application, as well as a new function to handle this functionality. 
- Added a new function `checkUncheckAll()` to handle the new "Check/Uncheck All" feature.
- Added new HTML to implement the "Check/Uncheck All" feature
Previously, users had to manually select each checkbox individually, which was time-consuming and prone to errors. This update makes the process faster and more user-friendly by allowing users to select or deselect all checkboxes with a single click.
Thank you for taking the time to review this pull request. We appreciate your feedback and suggestions.

Added check/uncheck functionality for all checkboxes

---

static/js/index.js
templates/add_build.html
templates/index.html

There are many paths in the application which were relative earlier. Those should be absolute. These need to be changed since we added a route recently and the paths (which were relative) would not lead to the right location from that route.

Fix incorrect relative paths

---

app.py

This updates branch list with 4.5.0 stable releases for Copter, Plane, Rover and Tracker.

Update branch list with latest releases

---

app.py

This function is no longer called anywhere in the code. I think I missed cleaning it up earlier.

Clean up unnecessary function

---

app.py

This adds the remotes mentioned in remotes.json to the local git repo in the base directory and fetches them on app start. Enables to build us for different remotes.
Should be merged after #79

Setup and fetch remotes other than `upstream` on load

---

app.py
remotes.json.sample
remotes.schema.json
scripts/fetch_releases.py

I mistyped it and it propagated through copy and paste to other places in the code. Apologies for not being careful.

Fix typo - 'artifacts' mistyped as 'atrifacts'

---

scripts/fetch_whitelisted_tags.py

This handles few edge cases to detect incomplete tags.
Also, adds few debug statements to help in future.

scripts: handle edge cases while adding custom-build/ tags 

---

ap_git/__init__.py
ap_git/core.py
ap_git/exceptions.py
ap_git/utils.py
app.py

This module will be used to perform git operations on a local repository. The operations would be performed using the subprocess calls under the hood. We will be able to perform parameter checking at code level and take appropriate actions before actually making the subprocess calls. This also gives us the ability to write custom procedures consisting of a series of git operations to achieve a desired result.

ap_git: module to perform git operations on a local repository

---

scripts/fetch_releases.py
scripts/fetch_whitelisted_tags.py

This PR refactors the existing Python script to allow it to be used both as a standalone script and as an importable module.

scripts: refactor fetch_xxx.py scripts for module compatibility

---

ap_git/core.py
app.py
metadata_manager/core.py
utils/__init__.py
utils/taskrunner.py

Currently, the scripts to fetch the versions are run as cron jobs. To make the setup easy, it would be nice to have them running inside the application under the recently added VersionsFetcher module.

Run version fetching jobs inside the application

---

scripts/fetch_releases.py
scripts/fetch_whitelisted_tags.py

scripts: change Tracker to AntennaTracker

---

metadata_manager/core.py

This will detect and initialize remotes.json if empty.

metadata_manager: ensure remotes.json file at initialisation

---

metadata_manager/__init__.py
metadata_manager/ap_src_meta_fetcher.py
metadata_manager/exceptions.py
metadata_manager/versions_fetcher.py

The VersionsFetcher and APSourceMetadataFetcher classes have grown too large, so it's time to move them into separate files.
The exceptions.py file did not contain any meaningful exceptions, so it has also been removed.

Refactor metadata-manager

---

build_manager/progress_updater.py
builder/builder.py
metadata_manager/__init__.py
metadata_manager/vehicles_manager.py
metadata_manager/versions_fetcher.py
scripts/fetch_releases.py
web/app.py

This class helps organise various attributes related to a vehicle, such as separating its display name from its waf target. It improves code structure by bundling vehicle-specific data in one place.

Add and use VehicleManager

---

scripts/fetch_releases.py

As pointed out by @peterbarker in #162, we need this to handle the corner cases.

scripts: fix versions comparison

---

web/static/js/add_build.js

Closes #171 
Show the stable versions first followed by beta and then the latest.
Do proper versions comparison instead of simple lexicographical string matching.
The new ordering would look like,

web: fix versions sorting

---

web/static/js/index.js
web/templates/index.html

... so that users do not have to worry about clicking the download button themselves.

web: try auto-download every 5 seconds for an ongoing build

---

builder/Dockerfile

Use new base image with ddsgen included

Builder: update base image for dds
