- app.py
This allows a build option for INA2xx battmon.  Likely needed for this user's issue on Discuss: [here](https://discuss.ardupilot.org/t/pixhawk-to-ina226/68577/11)
> APP: build options add HAL_BATTMON_INA2XX_ENABLED

- app.py
The current structure produces a method-on-None error in the case of an
exception in the protected blocks
> app.py: correct chained-exception problem

- .gitignore
- Vagrantfile
- scripts/initvagrant.sh
It's not pretty, but `vagrant up` will start a VM capable of using the custom build server.
Once the `up` is finished, the custom build server can be accessed by pointing a browser at http://localhost:8888/
> Vagrant: add Vagrant vm definition and creation script

- static/js/add_build.js
This adds a category wise _check/uncheck all_ checkbox that helps a user to check or uncheck all the options belonging to a particular category. 
This also takes care of dependency handling where all its dependencies needs to be checked when an option is selected using this operation and disabling the options which are dependent on another option when its unchecked using this operation.
I have tested this on my machine and it works fine. I would like to get this tested on beta server.
Thanks!
> Add category wise check-uncheck-all checkbox

- app.py
This fixes a bug causing incorrect reporting of build completion percentage in the status bar. 
The reason for the bug was incorrect regular expression which was not able to handle the leading spaces while parsing the fractions from the build log.
eg. `[   9/1000]` was not being matched by regular expression as it contains leading spaces before 9.
This should be merged after #46. Thanks!
> Fix bug causing incorrect reporting of build completion percentage in progress bar

- static/js/add_build.js
This allows all non-zero default values to check the corresponding checkbox for the option in the app. Thank you, @IamPete1, for submitting #38. The app has changed since the time you submitted that PR, so it needed to be reworked.
I tested it locally and it worked fine. On main, the geofence option was not being selected whereas on this branch it does.
Screenshot for main:-
Screenshot for this branch:-
> scripts: add_build.js: treat all non zero default values to be true

- app.py
This route is no longer used and was missed while cleaning up the unused code from the previous version of the app.
> app.py: remove old /view route

- static/js/add_build.js
The (global) check-uncheck-all button should be in sync with the number of options selected, i.e., if no option is selected then the global checkbox should also be unchecked, if all options are selected then the global checkbox should also get selected and if neither zero nor all options are selected, the global checkbox should remain in indeterminate state.
I have tested this work locally and it works fine. Everyone is welcome to test this on the beta server (custom-beta.ardupilot.org)
> add_build.js: Check uncheck all should reflect current state

- app.py
This allows a user to build the beta branches on custom build server.
> Allow builds on beta branches

- app.py
The log files were missing newlines and were having statements bleed over.
> Add missing newlines to log

- app.py
Improves error messages:
Try:
```
http://localhost:5000/get_allowed_branches/foo
```
Result now:
```
Bad Vehicle. Expected ['AntennaTracker', 'Blimp', 'Copter', 'Heli', 'Plane', 'Rover', 'Sub']
```
Previous Result:
```
Bad Vehicle
```
> Improve bad vehicle failure message

- README.md
- requirements.txt
This fixes numerous omitted steps that resulted in failed default behavior and replaces #61.
* No remote upstream added
* No requests library installed
* Converted from manual python deps install to a `requirements.txt` file (standard python practice)
* Added terminal commands to make it easier for ubuntu devs to get started with the custom build server
* spelling 
* no syntax highlighting for bash commands
Here is one failure, because the user never added `upstream` as a remote or fetched it:
```
$ ./app.py 
[2023-11-25 11:54:07,195] INFO in app: Creating /home/ryan/Dev/ros2_ws/src/base/builds
[2023-11-25 11:54:07,195] INFO in app: Got queue lock
[2023-11-25 11:54:07,221] INFO in app: Initial fetch
[2023-11-25 11:54:07,221] INFO in app: Running git rev-parse upstream/master in …
```
> Improve checkout/clone process to fix missing upstream

- static/js/add_build.js
This were probably used for debugging stuff and were mistakenly merged. Can be safely removed. Thanks!
> Remove leftover console.log statements used for debugging

- app.py
- remotes.json.sample
- remotes.schema.json
- requirements.txt
- static/js/add_build.js
- templates/add_build.html
This moves the dictionary we were using to list branches for builds outside of app.py. Major reasons for doing this are:
Configurations like these should not remain with the main application itself.
There is no point in versioning this information with git. This configuration keeps changing very regularly. Whenever we do releases, want to delist a branch, or make any other changes, this config changes.
We can update this file at regular intervals and reload the server to automatically sync with releases at firmware.ardupilot.org.
For this, I have made changes to the app to remove the dictionary from app.py and load it from remotes.json instead. We also validate this file against remotes.schema.json to ensure the structure of the file is correct and valid. I am working on a Python script …
> Move dictionary to list releases outside app.py and use a json file instead

- app.py
- remotes.json.sample
- remotes.schema.json
- scripts/fetch_releases.py
- scripts/fetch_releases_cronjob.sh
- scripts/fetch_whitelisted_tags.py
This script automates the listing of tagged versions of the ArduPilot source code from various white-listed forks from GitHub on the Custom Build Server. This is run by the same shell script which is runs as a cronjob and lists ardupilot official releases on custom build server. This uses GitHub api to fetch the tags, filters the tags based on conventions mentioned below and add entries in remotes.json accordingly.
Tag Naming Conventions:
- Tags named in the format `custom-build/xyz` are allowed to be built for all vehicles.
- Tags in the format `custom-build/vehicle/xyz` are allowed to be built for the specified vehicle only.
Examples:
- A tag named `custom-build/some-test-work` will be listed under all the vehicles.
- A tag named `custom-build/Copter/some-test-work` will be listed under …
> scripts: add a script to fetch and list tags from whitelisted repos

- scripts/fetch_whitelisted_tags.py
This removes all old tags and adds freshly fetched tags again for each remote.
> scripts: nuke old tags before adding new ones in fetch_whitelisted_tags.py 

- scripts/fetch_releases.py
- scripts/fetch_releases_cronjob.sh
This move the code to trigger quick reload of remotes.json out of fetch_releases.py. Now we have multiple scripts updating remotes.json. Hence, the bash script which runs as a cronjob and runs these python script should trigger a reload at the end instead of these scripts doing it individually.
Should be merged after #86
> scripts: move the code to trigger quick reload of remotes.json out of fetch_releases.py

- scripts/fetch_whitelisted_tags.py
We need to initialise this map with empty lists to make sure we still process the remotes and vehicles for which we do not find any new tags. If we don't do this, the method which updates remotes.json file simply skips those remotes and vehicles, which in turn leads to the tags that have been deleted stay there. So if we don't have any tags for a remote and vehicle, we specify it explicitly.
> scripts: initiliase empty versions map

- scripts/fetch_whitelisted_tags.py
This removes the word 'unreleased' from tag title in version-to-build dropdown.
> scripts: fetch_whitelisted_tags.py: remove 'unreleased' from tag title

- scripts/update_remotes_json_cronjob.sh
`fetch_whitelisted_tags.py` generate these log files. We need to include these files in the list of files to be cleaned up.
> scripts: cleanup fetch_whitelisted_tags_*.log files using crobjob script

- scripts/update_remotes_json_cronjob_beta.sh
- scripts/update_remotes_json_cronjob_main.sh
It would be nice to have separate crontab scripts for both instances of the application running on the autotest server, i.e., the one accessible at custom.ardupilot.org and custom-beta.ardupilot.org respectively.
> scripts: do seperate cronjob scripts for beta and main server

- app.py
We require this to make sure we fetch the tags which do not point to histories being fetched.
> app.py: add --tags and --force options to git fetch command

- app.py
We should always do force checkout to commits to avoid dirty working tree preventing checkouts.
> Fix dirty working tree preventing checkouts

- app.py
We need to move setting the logging configuration up to make sure the loggers initialised in other submodules after this setting can also use the same configuration.
> app.py: move setting the logging configuration up

- app.py
The metadata manager module takes care of checking out the requested version, this is redundant.
> app.py: remove redundant checkout call outside APSourceMetadataFetcher

- ap_git/core.py
We do checkouts in context of a remote (see [this](https://github.com/shiv-tyagi/CustomBuild/blob/6de3342ebd9cdfd6db98d57c5529bf13e85de537/ap_git/core.py#L415)).
Hence, the cloned repo should also have the remote added which contains the target commit to checkout.
> ap_git: add remote containing commit to copied repo on shallow clone

- .gitignore
- app.py
- scripts/fetch_releases.py
- scripts/fetch_whitelisted_tags.py
It is more intuitive to keep it inside the repo directory (and let git ignore it) unless explicitly specified.
> Chage default path for base directory

- web/app.py
We have moved app.py and hence the paths have changed.
> app.py: fix bin and cache dir paths

- web/app.py
If basedir option is not used, the default behaviour should be to try getting the path from the environment.
If still not found, default path should be used.
> web: allow setting BASEDIR through env

- ap_git/core.py
- web/app.py
This method would help in ensuring a git repository exists at a path before initialising a GitRepo object. Depending on the options passed, it will do a fresh clone if a git repo does not exist at a given path or is broken.
> Add and use GitRepo.clone_if_needed method

- metadata_manager/core.py
- web/app.py
The default board is not sourced from board_list.py, so setting it in metadata_manager makes no sense. The responsibility of metadata_manager is to simply pass the list of boards retrieved from board_list.py at a commit. The caller should determine which board to set as the default.
> Set default board in app.py instead of metadata_manager

- build_manager/__init__.py
- build_manager/cleaner.py
- build_manager/manager.py
- build_manager/progress_updater.py
- builder/__init__.py
- builder/__main__.py
- builder/builder.py
- builder/requirements.txt
- metadata_manager/__init__.py
- metadata_manager/core.py
- utils/__init__.py
- utils/ratelimiter.py
- web/app.py
- web/requirements.txt
- web/static/js/index.js
This PR introduces the build_manager and builder modules to the application, improving the build process by dedicating specific tasks to each and also clean up the app.py file.
- `build_manager` handles accepting build requests, queuing them, storing build metadata, and managing related tasks.
- `builder` is responsible for executing the actual builds.
To efficiently handle queuing, I've integrated Redis, a fast in-memory datastore. Since build metadata is frequently accessed, storing it in memory enhances performance. Additionally, Redis will also be used for caching the board and build options list (an upcoming PR will address this).
These modules contain sub-modules such as:
- `cleaner` – for cleaning up build artifacts.
- `progress_updater` – for tracking and updating build progress. …
> Add and use build_manager and builder modules

- utils/taskrunner.py
TaskRunner accepts a list of tasks which it executes at a given interval. Each TaskRunner object spawns a separate thread to execute the assigned list of tasks. With current design, if an exception occurs while executing any of the tasks, the thread dies and the other tasks would not execute due to that.
This change wraps those method calls inside a try-except block and just prints the exception when it occurs and keeps executing the tasks as expected.
> utils: wrap target method call in TaskRunner inside try-except

- metadata_manager/core.py
- web/app.py
The list of boards and build options remains the same for a given commit. This change caches them in Redis for 24 hours, allowing future requests for the boards list and build options to be served from the cache instead of checking out the Git repository each time.
Should be merged after #145
> Enable build options and board list caching

- docker-compose.yml
- web/Dockerfile
Let us not override command in docker-compose and use the same in dockerfile itself.
> Fix CMD in web/Dockerfile

- docker-compose.yml
- scripts/fetch_releases.py
- scripts/fetch_whitelisted_tags.py
We seem to be getting rate limited by github api sometimes due to a very low rate limit of 50 requests per hour for unauthenticated requests. With token, we get 5000 requests per hour.
> Use Github Access token for fetching tags
